name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.11.3

    # Build qmqtt
    - uses: actions/checkout@v2
      id: mqtt2qml_checkout
      with:
        path: 'qmqqt2qml'

    - name: Create QMQTT Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/${{mqtt2qml_checkout.path}}/build

    - name: Configure QMQTT CMake
      shell: bash
      working-directory: $GITHUB_WORKSPACE/${{mqtt2qml_checkout.path}}/build
      run: cmake $GITHUB_WORKSPACE/${{mqtt2qml_checkout.path}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build & install QMQTT
      shell: bash
      working-directory: $GITHUB_WORKSPACE/${{mqtt2qml_checkout.path}}/build

      run: cmake --build . --config $BUILD_TYPE --target install

    # Build qmqtt2qml
    - uses: actions/checkout@v2
      id: mqtt_checkout
      with:
        path: 'qmqtt'

    - name: Create Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/${{mqtt_checkout.path}}/build

    - name: Configure QMQTT CMake
      shell: bash
      working-directory: $GITHUB_WORKSPACE/${{mqtt_checkout.path}}/build
      run: cmake $GITHUB_WORKSPACE/${{mqtt_checkout.path}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: $GITHUB_WORKSPACE/${{mqtt2qml_checkout.path}}/build
      run: cmake --build . --config $BUILD_TYPE
