name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.11.3

    # Build qmqtt
    - uses: actions/checkout@v2
      name: Checkout qmqtt
      with:
        path: qmqtt
        repository: ejvr/qmqtt

    - name: Create QMQTT Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/qmqtt2qml/qmqtt/build

    - name: Configure QMQTT CMake
      shell: bash
      working-directory: ${{runner.workspace}}/qmqtt2qml/qmqtt/build
      run: cmake -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=OFF ..
 
    - name: Build & install QMQTT
      shell: bash
      working-directory: ${{runner.workspace}}/qmqtt2qml/qmqtt/build
      run: cmake --build . --config $BUILD_TYPE --target install

    # Build qmqtt2qml
    - uses: actions/checkout@v2
      name: Checkout qmqtt2qml
      with:
        path: qmqtt2qml

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/qmqtt2qml/qmqtt2qml/build

    - name: Configure QMQTT2QML CMake
      shell: bash
      working-directory: ${{runner.workspace}}/qmqtt2qml/qmqtt2qml/build
      run: cmake -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/qmqtt2qml/qmqtt2qml/build
      run: cmake --build . --config $BUILD_TYPE
