name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.11.3

    # Build qmqtt
    - uses: actions/checkout@v2
      name: Checkout qmqtt
      with:
        path: qmqtt
        repo: ejvr/qmqtt

    - name: Create QMQTT Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/qmqtt/build

    - name: Configure QMQTT CMake
      shell: bash
      working-directory: $GITHUB_WORKSPACE/qmqtt/build
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE/qmqtt
 
    - name: Build & install QMQTT
      shell: bash
      working-directory: $GITHUB_WORKSPACE/qmqtt/build
      run: cmake --build $GITHUB_WORKSPACE/qmqtt/build --config $BUILD_TYPE --target install

    # Build qmqtt2qml
    - uses: actions/checkout@v2
      name: Checkout qmqtt2qml
      with:
        path: qmqqt2qml

    - name: Create Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/qmqqt2qml/build

    - name: Configure QMQTT CMake
      shell: bash
      working-directory: $GITHUB_WORKSPACE/qmqqt2qml/build
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE/qmqqt2qml/build

    - name: Build
      shell: bash
      working-directory: $GITHUB_WORKSPACE/qmqqt2qml/build
      run: cmake --build $GITHUB_WORKSPACE/qmqqt2qml/build --config $BUILD_TYPE
